version: "3.8"
services:
  consul:
    image: consul
    ports:
      - "8500:8500"
  xtrackdb:
    image: postgres
    volumes:
      - "$PWD/postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xtrackdb
    depends_on:
      - "consul"
  xtrack:
    build: ./web4
    image: phi180/x-track
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILE=docker
    depends_on:
      - "consul"