// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "c3e9a9f7-0dfd-45cf-8e83-2d449c81475b");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.background.lastInstalledTaskVersion", 3);
user_pref("app.update.background.previous.reasons", "[\"app.update.langpack.enabled=true and at least one langpack is installed\"]");
user_pref("app.update.background.rolledout", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1669020718);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1669020690);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1669020958);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1669020838);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1669020748);
user_pref("app.update.lastUpdateTime.telemetry_untrustedmodules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir3.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{e4ad1ed8-fc71-4ff0-8dd1-c16a0781f4ed}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1669020687);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 132);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6de3c20d-d7ed-495d-86cc-36de671c918b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.privacySegmentation.createdShortcut", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1669020689);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1669020702802");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1669022501802");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1669020691070");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1669042291070");
user_pref("browser.search.region", "IT");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20221110173214");
user_pref("browser.startup.homepage_override.mstone", "107.0");
user_pref("browser.startup.homepage_override.once", "{\"message_id\":\"WNP_MOMENTS_13\",\"url\":\"https://www.mozilla.org/firefox/welcome/13\",\"expire\":1640908800000}");
user_pref("browser.startup.lastColdStartupCheck", 1669020689);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 4);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1669020689373");
user_pref("distribution.iniFile.exists.appversion", "107.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "IT");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "9ab7a31f3e9e42abb05a54ee380f1e49");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221110173214");
user_pref("extensions.lastAppVersion", "107.0");
user_pref("extensions.lastPlatformVersion", "107.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"4987d697-e90a-4014-9872-3544a15c91c7\",\"pictureinpicture@mozilla.org\":\"64fbc208-e2dc-4b6e-a544-8541f65b697f\",\"screenshots@mozilla.org\":\"44b88739-ea2e-44e9-ae9b-d1963ceb094a\",\"webcompat-reporter@mozilla.org\":\"ef051d22-c5b9-42fb-ad32-310349ef445e\",\"webcompat@mozilla.org\":\"dd7b05ad-36ac-4a54-8a50-a44dd77058c3\",\"default-theme@mozilla.org\":\"23300756-7186-473a-9aa6-5cf95a1e69b9\",\"addons-search-detection@mozilla.com\":\"b91c2aeb-e67f-4045-af02-46062eb0dcad\",\"google@search.mozilla.org\":\"44bc0a51-378b-4d52-a192-07ea6383d21e\",\"wikipedia@search.mozilla.org\":\"2e4b1e86-b4a2-4e9c-af9e-b095ae26d2fd\",\"bing@search.mozilla.org\":\"ca42a55e-456f-4d52-9913-d79822d2d344\",\"ddg@search.mozilla.org\":\"8be632da-3c81-4c0c-9fed-ffc044d25c90\",\"ebay@search.mozilla.org\":\"3f48046a-0054-4211-99a3-e47c22fa1deb\",\"amazon@search.mozilla.org\":\"da683042-3ffc-496e-8c34-a2689bf13d62\",\"uBlock0@raymondhill.net\":\"2ea8b733-cd81-4475-ae48-c2ac3bfe3d66\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1669020689);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx-shader-check.build-version", "20221110173214");
user_pref("gfx-shader-check.device-id", "0x9a49");
user_pref("gfx-shader-check.driver-version", "31.0.101.3430");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", true);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.device-id", "0x9a49");
user_pref("sanity-test.driver-version", "31.0.101.3430");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20221110173214");
user_pref("security.sandbox.content.tempDirSuffix", "{20bd6d2a-3a77-49d8-913e-df878598c4d8}");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1669020687);
user_pref("toolkit.telemetry.cachedClientID", "a419d671-68c0-4a28-ad42-ac203ae1da81");
user_pref("toolkit.telemetry.previousBuildID", "20221110173214");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Keyboard presence confirmed.");
