# application.yml
---
spring:
  application:
    name: web4
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/xtrackdb
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        ddl-auto: drop-create
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
  thymeleaf:
    encoding: UTF-8
    enabled: 'true'
    prefix: classpath:/templates/
    cache: 'false'
    check-template-location: 'true'
    suffix: .html
    servlet:
      content-type: text/html
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instanceId: ${spring.application.name}-${spring.cloud.client.hostname}-${random.value}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        # configurazione per effettuare esprimenti, NON USARE UN PRODUZIONE
        # dopo quanto tempo consul deve smettere di restituire servizi che non rispondono all'health check?
        healthCheckCriticalTimeout: 45s
        # consul deve restituire solo servizi che passano l'health check (default=false)
        queryPassing: true
    loadbalancer:
      ribbon.enabled: false


server:
  #port: ${PORT:${SERVER_PORT:0}}
  port: 8080
  servlet:
    context-path: /


